title: "Your Mate Handyman"
description: "Reliable • Friendly • Local"
remote_theme: pages-themes/minimal@v0.2.0
plugins: [jekyll-remote-theme]
include:
  - "_layouts"
  - "_includes"
  - "_pages"
  - "_projects"
  - "_testimonials"
  - "assets/images"
