title: "Your Mate Handyman"
description: "Reliable • Friendly • Local"
remote_theme: pages-themes/minimal@v0.2.0
plugins: [jekyll-remote-theme]
# Note: Do not include internal Jekyll folders. They are processed automatically
# and should not be published to _site. Static assets under assets/ are copied by default.
# If this is a project site, set url/baseurl accordingly:
# url: "https://radik097.github.io"
# baseurl: "/Stan"
